---
- name: Submit s3 batch operation via awscli
  shell: >
    aws s3control create-job
    --region {{ __s3_batch_op.region | d (default_s3_batch_op_region) }}
    --account-id {{ __s3_batch_op.account_id | d (default_s3_batch_op_account_id) }}
    --operation {{ __s3_batch_op.operation | to_json | quote }}
    --manifest {{ manifest }}
    --report {{ __s3_batch_op.report | to_json | quote }}
    --role-arn {{ __s3_batch_op.role_arn | d (default_s3_batch_op_role_arn) }}
    {{ (tags_query != '') | ternary (tags, '') }}
    {{ (priority_query != '') | ternary (priority, '') }} 
    {{ (description_query != '') | ternary (description, '') }} 
    --no-confirmation-required
  vars:
    tags: '--tags {{ tags_query }}'
    tags_query: '{{ __s3_batch_op | json_query("tags") }}'
    priority: '--priority {{ priority_query }}'
    priority_query: '{{ __s3_batch_op | json_query("priority") }}'
    description: '--description {{ description_query | quote }}'
    description_query: '{{ __s3_batch_op | json_query("description") }}'
    manifest: '{{ __s3_batch_op.manifest | to_json | quote }}'
  register: batch_operation_fact

- name: Set job_id
  set_fact:
    job_id: '{{ (batch_operation_fact.stdout | from_json).JobId }}'
  
- name: Describe job
  shell: >
    aws s3control describe-job
    --region {{ __s3_batch_op.region | d (default_s3_batch_op_region) }}
    --account-id {{ __s3_batch_op.account_id | d (default_s3_batch_op_account_id) }}
    --job-id {{ job_id }}
  register: describe_job
  until: status == 'Completed' or status == 'Failed'
  retries: '{{ describe_job_retries }}'
  delay: '{{ describe_job_delay }}'
  vars:
    job: '{{ (describe_job | from_json).Job }}'
    status: '{{ job["Status"] }}'
  
- name: Set batch operation job
  set_fact:
    s3_batch_op_job: '{{ (describe_job | from_json).Job }}'

- debug:
    var: s3_batch_op_job

  