---
- name: Submit batch tagging via awscli
  shell: >
    aws s3control create-job --region {{ item.region | d (s3_batch_operation.region) }} --account-id {{ item.account_id | | d (s3_batch_operation.account_id) }} 
    --operation {{ item.operation.to_json }} --manifest {{ item.manifest.to_json }} --report {{ item.report.to_json }} --role-arn {{ item.role_arn | d (s3.batch_operation.role_arn) }} 
    {{ (item.priority is defined) | ternary (priority, '') }} {{ (item.description is defined) | ternary (description, '') }} --no-confirmation-required
  vars:
    priority: '--priority {{ item.priority }}'
    description: '--description {{ item.description }}'
  loop: '{{ s3_batch_operations }}'

  