---
- name: Submit s3 batch operation via awscli
  shell: >
    aws s3control create-job
    --region {{ __s3_batch_op.region | d (default_s3_batch_op_region) }}
    --account-id {{ __s3_batch_op.account_id | d (default_s3_batch_op_account_id) }}
    --operation {{ __s3_batch_op.operation | to_json | quote }}
    --manifest {{ manifest }}
    --report {{ __s3_batch_op.report | to_json | quote }}
    --role-arn {{ __s3_batch_op.role_arn | d (default_s3_batch_op_role_arn) }}
    {{ (tags_query != '') | ternary (tags, '') }}
    {{ (priority_query != '') | ternary (priority, '') }} 
    {{ (description_query != '') | ternary (description, '') }} 
    --no-confirmation-required
  vars:
    tags: '--tags {{ tags_query }}'
    tags_query: '{{ __s3_batch_op | json_query("tags") }}'
    priority: '--priority {{ priority_query }}'
    priority_query: '{{ __s3_batch_op | json_query("priority") }}'
    description: '--description {{ description_query | quote }}'
    description_query: '{{ __s3_batch_op | json_query("description") }}'
    manifest: '{{ __s3_batch_op.manifest | to_json | quote }}'
  register: batch_operation_fact

- debug:
    var: batch_operation_fact

- name: Display JobID repsonse
  debug:
    msg: 'The job id is {{ batch_operation_fact.stdout | from_json }}'

  