---
- name: Assert that location and Location are exclusive (1st)
  assert:
    that:
      - s3_batch_op.manifest.Location is undefined
    fail_msg: 'location and manifest.Location are exclusive options, please remove one'
    quiet: yes
  when: s3_batch_op.location is defined

- name: Assert that location and Location are exclusive (2nd)
  assert:
    that:
      - s3_batch_op.location is undefined
    fail_msg: 'location and manifest.Location are exclusive options, please remove one'
    quiet: yes
  when: s3_batch_op.manifest.Location is defined
