---

- name: List objects in report prefix
  aws_s3:
    bucket: cor-s3-inventory-1
    prefix: fedora-cor-arch-binaries/completion-report/
    mode: list
  register: completion_report

- set_fact:
    report_key: '{{ completion_report.s3_keys | d (False) | select("contains", job_id) | select ("contains", ".csv") | list | last | d ("none") }}'
  vars:
    job_id: 8f25a41b-9792-4652-a00d-1a2ce556ce96

- name:
  debug:
    msg: '{{ report_key }}'
  #vars:
  #  report_key: fedora-cor-arch-binaries/completion-report/job-8f25a41b-9792-4652-a00d-1a2ce556ce96/results/7ee0abc5656ec05983399483b9ef2c2e5e3b37a4.csv

- pause:


- name: Assert that location and Location are exclusive (1st)
  assert:
    that:
      - s3_batch_op.manifest.Location is undefined
    fail_msg: 'location and manifest.Location are exclusive options, please remove one'
    quiet: yes
  when: s3_batch_op.location is defined

- name: Assert that location and Location are exclusive (2nd)
  assert:
    that:
      - s3_batch_op.location is undefined
    fail_msg: 'location and manifest.Location are exclusive options, please remove one'
    quiet: yes
  when: s3_batch_op.manifest.Location is defined

- name: Assert that submit only is false when requesting report links
  assert:
    that: not s3_batch_op_submit_only
    fail_msg: Requesting report links requires that s3_batch_op_submit_only be set to false. Please change and restart.
    quiet: yes
  when: s3_batch_op_generate_direct_download or s3_batch_op_generate_console_download