---
- name: List objects in location KeyPrefix
  aws_s3:
    bucket: 'arn:aws:s3:::cor-s3-inventory-1'
    prefix: 'fedora-cor-arch-binaries/completion-report'
    mode: list
  #vars:
  #  key: '{{ s3_batch_op.location.KeyPrefix }}'
  register: completion_report