---
- name: List objects in Location Key
  aws_s3:
    bucket: '{{ key.split("/")[0] }}'
    prefix: '{{ key.split("/")[1:] | join("/") }}'
    mode: list
  vars:
    key: '{{ manifest.Location.Date.Key }}'
  loop: '{{ s3_batch_operations }}'
  register: list_keys
  when: manifest.Location.Date is defined

- debug:
    var: list_keys

- name: Create new s3_batch_operations with associated keys
  set_fact:
    __s3_batch_operations: '{{ __s3_batch_operations | d([]) + [item.0 | combine({"checksum_key": item.1.s3_keys | d (False) | select("contains", checksum_search) | list | last | d (False) })] }}'
  vars:
    checksum_search: '{{ manifest_conditional | ternary("manifest.checksum", checksum_full) }}'
    checksum_full: '{{ manifest_string }}/manifest.checksum'
    manifest: '{{ item.0.manifest | d (s3_batch_operation.manifest) }}'
    manifest_conditional: '{{ manifest_date.Latest | d (False) }}'
    manifest_date: '{{ manifest.Location.Date | d () }}'
    manifest_string: '{{ manifest_date.Year | d () }}-{{ manifest_date.Month | d () }}-{{ manifest_date.Day | d () }}T00-00Z'
  loop: '{{ s3_batch_operations | zip(list_keys.results) | list }}'

- debug:
    var: __s3_batch_operations
- pause: