---
- name: List objects in Location Key
  aws_s3:
    bucket: '{{ key.split("/")[0] }}'
    prefix: '{{ key.split("/")[1:] | join("/") }}'
    mode: list
  vars:
    key: '{{ manifest.Location.Key }}'
  loop: '{{ s3_batch_operations }}'
  register: list_keys
  when: item.Location.Date is defined

- debug:
    var: list_keys

- pause: